server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-suffix-path: true
        cors-configurations:
          '[/**]':
            # CHANGE THIS LINE: use allowedOriginPatterns instead of allowedOrigins
            allowedOriginPatterns: "*" 
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: angular-service
          uri: lb://ANGULAR-SPRING-SERVICE
          predicates:
            - Path=/api/angular/**
          filters:
            - RewritePath=/api/angular/(?<segment>.*), /${segment}

        - id: react-service
          uri: lb://REACT-SPRING-SERVICE
          predicates:
            - Path=/api/react/**
          filters:
            - RewritePath=/api/react/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info